spring:
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: oauth-server  # Asegúrate de que esto coincida
            client-id: oauth-client
            client-secret: 12345678910
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            client-name: oauth-client
            scope: openid,profile,read,write
        provider:
          oauth-server:  # Debe coincidir con el provider usado en registration
            issuer-uri: http://127.0.0.1:9000
